# Generated by Django 5.0.6 on 2024-05-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0002_game_screenshots_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshots',
            new_name='Screenshot',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
