# Generated by Django 5.0.6 on 2024-05-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0003_rename_screenshots_screenshot_rename_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
