# Generated by Django 5.0.6 on 2024-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0004_alter_game_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
