# Generated by Django 5.0.6 on 2024-05-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0006_alter_game_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='storyline',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
