# Generated by Django 5.0.6 on 2024-05-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0008_alter_game_storyline_alter_game_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
