# Generated by Django 5.0.6 on 2024-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0013_alter_game_first_released_alter_game_genres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='igdb.genre'),
        ),
    ]
