# Generated by Django 5.0.6 on 2024-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0014_genre_remove_game_genres_game_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, to='igdb.genre'),
        ),
    ]
