# Generated by Django 4.2.13 on 2024-06-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0016_alter_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='storyline',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
