# Generated by Django 4.2.13 on 2024-06-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0017_alter_game_storyline_alter_game_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='storyline',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
