# Generated by Django 4.2.13 on 2024-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0018_alter_game_storyline_alter_game_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
