# Generated by Django 4.2.13 on 2024-06-27 16:55

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0019_alter_game_name'),
    ]

    operations = [
        BtreeGinExtension(),
         migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS pg_trgm;',
            
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='game_name_gin_trgm_index', opclasses=['gin_trgm_ops']),
        ),
    ]
