# Generated by Django 4.2.13 on 2024-07-04 01:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0020_game_game_name_gin_trgm_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='game_name_gin_trgm_index',
        ),
        migrations.AddField(
            model_name='game',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='igdb_game_name_31d37d_gin'),
        ),
    ]
