# Generated by Django 4.2.13 on 2024-07-04 16:29

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0021_remove_game_game_name_gin_trgm_index_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='igdb_game_name_31d37d_gin',
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='igdb_game_search__7feaa9_gin'),
        ),
    ]
