# Generated by Django 4.2.13 on 2024-07-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdb', '0028_alter_game_cover_url_alter_game_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, to='igdb.genre'),
        ),
    ]
