# Generated by Django 5.0.6 on 2024-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/blank-profile-picture.png', upload_to='images'),
        ),
    ]
